# Site settings
name: Atharv Gupta
title: Atharv Gupta | [Not-So]-Average
description: I"'"m Atharv Gupta, a [not-so]-average teen who loves everything music & sports-related. I also like working out! 
url: https://atharvgups.github.io/
baseurl: ''
email: atharvgups@gmail.com
cover: https://atharvgups.github.io/img/og.png
logo: https://atharvgups.github.io/img/logo.png
social:
  - title: email
    url: mailto:atharvgups@gmail.com
  - title: spotify
    url: https://open.spotify.com/user/5s6cocuc2wi8541o0skac5rf6
  - title: unsplash
    url: https://unsplash.com/@atharvgups
  - title: github
    url: https://github.com/atharvgups
    
# Build settings
markdown: kramdown

exclude:
  - 'Gemfile'
  - 'Gemfile.lock'
  - '*.gemspec'
  - 'README.md'
  - 'node_modules'
  - 'build'
  - 'gulpfile.js'
  - 'package.json'

keep_files:
  - 'CNAME'
  - '.git'
  - '.gitignore'

plugins_dir:
  - jekyll-minifier
  - jekyll-sitemap
