# Site settings
name: Atharv Gupta
title: Atharv Gupta
description: "Atharv Gupta is an Applied and Computational Math student at UC Irvine, interning at Simula and building Zot Eats for Anteaters."
url: https://atharvgups.github.io/
baseurl: ''
email: atharvgups@gmail.com
resume: /files/Atharv_Gupta_Resume.pdf
cover: https://atharvgups.github.io/img/og.png
logo: https://atharvgups.github.io/img/logo.svg
social:
  - title: email
    url: mailto:atharvgups@gmail.com
  - title: linkedin
    url: https://www.linkedin.com/in/gupta-atharv/
  - title: github
    url: https://github.com/atharvgups

# Build settings
markdown: kramdown

exclude:
  - 'Gemfile'
  - 'Gemfile.lock'
  - '*.gemspec'
  - 'README.md'
  - 'node_modules'
  - 'build'
  - 'gulpfile.js'
  - 'package.json'

keep_files:
  - 'CNAME'
  - '.git'
  - '.gitignore'

plugins:
  - jekyll-sitemap
